message:
  prefix: "[PlayTimeTracker]"

  have-reward-redeem: "You have the following unacquired rewards, use `/ptt acquire [name]` to acquire"
  have-reward-redeem-format: "- %s"
  rule-applied: "Congratulations! The following rule has applied to you: %s"
  nothing-to-acquire: "You have nothing to acquire"
  cannot-acquire: "You can not acquire %s now"
  no-such-rule: "Rule not found"

  only-player-can-do: "Only players can do this"
  no-permission: "You are not allowed to do this"
  reload-finished: "Reload finished"
  command-done: "Command executed successfully"

  statistic-for: "Statistic for player: %s"
  statistic-day: "Online time today: %s"
  statistic-week: "Online time this week: %s"
  statistic-month: "Online time this month: %s"
  statistic-session: "Online time this session: %s"
  statistic-total: "Online time total: %s"
  statistic-time-format:
    ms: "%dms"
    s: "%dseconds "
    m: "%dminutes "
    h: "%dhours "
    zero: "No Record"
  statistic-no-record: "No record for that player."

  no-player: "Player not found."
  invalid-rule: "Not a valid disposable reward rule"

check-afk: true
use-ess-afk-status: false
afk-time: 180 #seconds
afk-check-interval: 30 #seconds
cancel-afk-on:
  chat: true
  command: true
  move: true
save-interval: 60 #seconds
display-on-login: false

rewards:
  some-reward:
    description: "You were given one stone."
    command: "give {playerName} 1 1"
  another-reward:
    description: "You were give two stones"
    command: "give {playerName} 1 2"
  third-reward:
    description: ""
    command: "broadcast {playerName} has been online for one hour!"


rules:
  rule1: # rule name cannot contains space ` ` and comma `,`
    period: "day" # week|month|disposable|session
    require: 60 # total online *minutes* to meet the reward requirement
    auto-give: false # automatically give the reward
    timeout: 60 # the time player able to acquire the reward, in minutes.
                # Ignored when auto-give is true. Omit this means "unlimited".
                # Always timeout at the end of each period
    reward: some-reward
  rule2:
    period: "disposable"
    require: 60
    auto-give: true
    reward: third-reward
  rule3:
    period: "longtimenosee" # rewards are given when players back after a long period time of away
    require: 60 # how long the player left, *IN DAYS*
    auto-give: true
    eligible-group: [group1,group2] # only players in groups listed here can acquire the rule. Any one can acquire if omitted.
    reward: another-reward
